import { CURRENT_SCHEMA_VERSION, DEFAULT_SETTINGS } from "./constants";
import type { AppState, AvailabilityBlock, Session, Student } from "./types";

const colors = ["sky", "violet", "amber", "emerald", "rose", "slate"] as const;

const students: Student[] = [
  {
    id: "demo-stu-01",
    name: "Nina",
    grade: "2nd",
    teacher: "Ms. Avery",
    requiredMinutesPerWeek: 120,
    preferredSessionLength: 30,
    sessionType: "group",
    unavailableBlockIds: [],
    notes: "Fictional sample — prefers mornings.",
    color: colors[0],
  },
  {
    id: "demo-stu-02",
    name: "Kai",
    grade: "3rd",
    teacher: "Mr. Brooks",
    requiredMinutesPerWeek: 90,
    preferredSessionLength: 30,
    sessionType: "individual",
    unavailableBlockIds: [],
    notes: "",
    color: colors[1],
  },
  {
    id: "demo-stu-03",
    name: "Rio",
    grade: "1st",
    teacher: "Rm 204",
    /** Tuned so Tue + Wed lunch session = exactly required (lunch still flags overlap). */
    requiredMinutesPerWeek: 55,
    preferredSessionLength: 30,
    sessionType: "flexible",
    unavailableBlockIds: [],
    notes: "",
    color: colors[2],
  },
  {
    id: "demo-stu-04",
    name: "Mo",
    grade: "5th",
    teacher: "Ms. Avery",
    requiredMinutesPerWeek: 30,
    preferredSessionLength: 30,
    sessionType: "individual",
    unavailableBlockIds: ["blk-art-demo"],
    notes: "Fictional pull-out tie-in for the sample.",
    color: colors[3],
  },
  {
    id: "demo-stu-05",
    name: "Tess",
    grade: "K",
    teacher: "Ms. Chen",
    requiredMinutesPerWeek: 30,
    preferredSessionLength: 30,
    sessionType: "group",
    unavailableBlockIds: [],
    notes: "",
    color: colors[4],
  },
  {
    id: "demo-stu-06",
    name: "Owen",
    grade: "4th",
    teacher: "Mr. Diaz",
    requiredMinutesPerWeek: 30,
    preferredSessionLength: 30,
    sessionType: "individual",
    unavailableBlockIds: [],
    notes: "",
    color: colors[5],
  },
  {
    id: "demo-stu-07",
    name: "Lane",
    grade: "2nd",
    teacher: "Ms. Avery",
    requiredMinutesPerWeek: 120,
    preferredSessionLength: 30,
    sessionType: "flexible",
    unavailableBlockIds: [],
    notes: "Sample: still needs more weekly minutes.",
    color: colors[0],
  },
  {
    id: "demo-stu-08",
    name: "Sky",
    grade: "3rd",
    teacher: "Rm 112",
    requiredMinutesPerWeek: 60,
    preferredSessionLength: 30,
    sessionType: "individual",
    unavailableBlockIds: [],
    notes: "",
    color: colors[1],
  },
  {
    id: "demo-stu-09",
    name: "JC",
    grade: "K–2",
    teacher: "Team caseload",
    requiredMinutesPerWeek: 45,
    preferredSessionLength: 30,
    sessionType: "individual",
    unavailableBlockIds: [],
    notes: "Initials only — fictional sample.",
    color: colors[2],
  },
  {
    id: "demo-stu-10",
    name: "Zee",
    grade: "4th",
    teacher: "Paras",
    requiredMinutesPerWeek: 90,
    preferredSessionLength: 30,
    sessionType: "individual",
    unavailableBlockIds: [],
    notes: "Fictional sample student.",
    color: colors[3],
  },
];

/** Six blocks: five school-wide + one student-specific (art pull-out). */
const availabilityBlocks: AvailabilityBlock[] = [
  {
    id: "blk-recess-demo",
    label: "Recess",
    type: "recess",
    dayOfWeek: 1,
    startTime: "10:00",
    endTime: "10:30",
    appliesTo: "global",
  },
  {
    id: "blk-lunch-demo",
    label: "Lunch",
    type: "lunch",
    dayOfWeek: 2,
    startTime: "11:30",
    endTime: "12:15",
    appliesTo: "global",
    notes: "Whole school (sample)",
  },
  {
    id: "blk-testing-demo",
    label: "Building testing window",
    type: "testing",
    dayOfWeek: 3,
    startTime: "09:30",
    endTime: "11:30",
    appliesTo: "global",
  },
  {
    id: "blk-specials-demo",
    label: "Specials rotation",
    type: "specials",
    dayOfWeek: 3,
    startTime: "13:00",
    endTime: "13:45",
    appliesTo: "global",
  },
  {
    id: "blk-art-demo",
    label: "Art pull-out (Mo)",
    type: "specials",
    dayOfWeek: 0,
    startTime: "13:00",
    endTime: "13:45",
    appliesTo: "student",
    studentIds: ["demo-stu-04"],
    notes: "Fictional pull-out",
  },
  {
    id: "blk-meeting-demo",
    label: "Meetings / paperwork",
    type: "slp_unavailable",
    dayOfWeek: 4,
    startTime: "08:00",
    endTime: "09:00",
    appliesTo: "slp",
    notes: "Sample SLP hold",
  },
];

const sessions: Session[] = [
  { id: "ses-demo-kai", dayOfWeek: 0, startTime: "08:30", endTime: "09:00", studentIds: ["demo-stu-02"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-nina-am", dayOfWeek: 0, startTime: "09:00", endTime: "09:30", studentIds: ["demo-stu-01"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-sky", dayOfWeek: 0, startTime: "10:30", endTime: "11:30", studentIds: ["demo-stu-08"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-art", dayOfWeek: 0, startTime: "13:15", endTime: "13:45", studentIds: ["demo-stu-04"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-big", dayOfWeek: 0, startTime: "14:00", endTime: "14:30", studentIds: ["demo-stu-01", "demo-stu-02", "demo-stu-05", "demo-stu-06", "demo-stu-08"], sessionType: "group", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-lane", dayOfWeek: 1, startTime: "10:30", endTime: "11:15", studentIds: ["demo-stu-07"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-rio-tue", dayOfWeek: 1, startTime: "14:00", endTime: "14:30", studentIds: ["demo-stu-03"], sessionType: "flexible", location: "Hallway", countsTowardMinutes: true },
  { id: "ses-demo-empty", dayOfWeek: 1, startTime: "15:00", endTime: "15:30", studentIds: [], sessionType: "group", countsTowardMinutes: false },
  { id: "ses-demo-zee-b", dayOfWeek: 1, startTime: "09:00", endTime: "09:30", studentIds: ["demo-stu-10"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-owen-wed", dayOfWeek: 2, startTime: "09:00", endTime: "09:30", studentIds: ["demo-stu-06"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-nina-wed", dayOfWeek: 2, startTime: "10:00", endTime: "10:30", studentIds: ["demo-stu-01"], sessionType: "group", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-rio-lunch", dayOfWeek: 2, startTime: "11:45", endTime: "12:10", studentIds: ["demo-stu-03"], sessionType: "group", location: "Hallway table", countsTowardMinutes: true },
  { id: "ses-demo-jc", dayOfWeek: 3, startTime: "12:00", endTime: "12:45", studentIds: ["demo-stu-09"], sessionType: "individual", location: "Rm 112", countsTowardMinutes: true },
  { id: "ses-demo-thu", dayOfWeek: 3, startTime: "14:00", endTime: "14:30", studentIds: ["demo-stu-01", "demo-stu-05"], sessionType: "group", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-to", dayOfWeek: 4, startTime: "10:00", endTime: "10:30", studentIds: ["demo-stu-05", "demo-stu-06"], sessionType: "group", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-zee-a", dayOfWeek: 0, startTime: "15:00", endTime: "16:00", studentIds: ["demo-stu-10"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
  { id: "ses-demo-kai-tue", dayOfWeek: 1, startTime: "08:00", endTime: "08:30", studentIds: ["demo-stu-02"], sessionType: "individual", location: "Speech room", countsTowardMinutes: true },
];

/**
 * Fictional sample for “View demo” — tuned for a small set of clear conflicts.
 * IDs match `OFFICIAL_DEMO_STUDENT_ID_LIST` in constants.
 */
export const demoAppState: AppState = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  onboardingCompleted: true,
  students,
  availabilityBlocks,
  sessions,
  settings: {
    ...DEFAULT_SETTINGS,
    maxGroupSize: 4,
    slpDisplayName: "Sample SLP (fictional)",
  },
};

export const emptyAppState: AppState = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  onboardingCompleted: false,
  students: [],
  availabilityBlocks: [],
  sessions: [],
  settings: { ...DEFAULT_SETTINGS },
};
